stages:
  - build
  - publish

variables:
  RUST_IMAGE: "rust:latest"

before_script:
  - rustup component add clippy
  - rustup component add rustfmt
  - mkdir -p .cargo

build:
  image: $RUST_IMAGE
  stage: build
  tags:
    - build
  script:
    - cargo build --release
    - cargo fmt -- --check
    - cargo test
  only:
    - branches

build-and-publish-to-crates-io:
  image: $RUST_IMAGE
  stage: publish
  tags:
    - build
  script:
    - echo "Update Cargo.toml version to $CI_COMMIT_TAG"
    - sed -i "s/^version = \".*\"/version = \"$CI_COMMIT_TAG\"/" Cargo.toml
    - cat Cargo.toml
    - cargo build --release
    - cargo fmt -- --check
    - cargo package --allow-dirty
    - cargo publish --allow-dirty --token $CARGO_REGISTRY_TOKEN
  only:
    - tags
